### ISSUE TITLE
Support for RG name in outputs.tf

### ISSUE THREAD

**Issue by shahar5** [Azure/terraform-azurerm-vnet#166]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description

Needed when you have to assign the right RG and VNet dynamically during resource creation, and you have to loop over multiple VNets

### New or Affected Resource(s)/Data Source(s)

azurerm_virtual_network.vnet.resource_group_name

### Potential Terraform Configuration

```hcl
output "resource_group_name" {
  description = "The name of the resource group in which the virtual network was created"
  value       = azurerm_virtual_network.vnet.resource_group_name
}
```

**Comment by lonegunmanb** [comment]
Thanks @shahar5 for opening this issue to us and apologies for this late reply. After reviewing this issue I decide not to bring this feature to this module, since the virtual network's resource group name is set by the input variable `var.resrouce_group_name`, so I cannot see the value of exposing this variable's value as output. Please feel free to reopen this issue if you have different thought.
