### ISSUE TITLE
Subnet resources recreated when network list modified

### ISSUE THREAD

**Issue by zette** [Azure/terraform-azurerm-vnet#52]
`resource "azurerm_subnet" "subnet"` block should use `for_each` instead of `count` for creating subnet resources.
With count all subnets are recreated when the provided list of subnets to create is modified, which can be breaking change in live environment.

**Comment by carlosdoliveira** [comment]
Totally agree. I've been working in a new way to create Virtual Networks and Subnets by using `for_each` and it's waay better.

**Comment by LaurentLesle** [comment]
You can explore the terraform  moved block to support the refactoring. Requires terraform 1.1 at minimum https://www.terraform.io/language/modules/develop/refactoring

**Comment by holms** [comment]
Is this module even maintained? No reaction for the whole year?

**Comment by lonegunmanb** [comment]
> You can explore the terraform moved block to support the refactoring. Requires terraform 1.1 at minimum https://www.terraform.io/language/modules/develop/refactoring

Unfortunately, I haven't seen a solution to refactor this module from `count` to `for_each` since we have no idea about the content of list. The only way to do that is declare the `moved` block in root module.

I'd like to keep this module with `count`, and create a new, "modern" version using `for_each`. After that we should use the new module for new stack.

I'm closing this issue now because we have nothing to do without breaking user's infrastructure. If you have a better solution, please feel free to open a new issue or pr, thanks folks!
